version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: travelore-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    environment:
      - MONGO_INITDB_DATABASE=travelore

volumes:
  mongodb_data: 