'use client';

import { motion } from 'framer-motion';

const MotionDiv = motion.div;

export function FeaturesSection() {
    return (
        <section className="py-24 px-4">
            <div className="max-w-7xl mx-auto">
                <h2 className="text-4xl font-bold text-center mb-16">
                    Revolutionizing Travel Content
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
                    {/* AI-Generated Content */}
                    <MotionDiv
                        whileHover={{ y: -10 }}
                        className="p-6 rounded-2xl bg-white shadow-xl"
                    >
                        <div className="h-12 w-12 bg-purple-100 rounded-xl flex items-center justify-center mb-4">
                            <span className="text-2xl">🤖</span>
                        </div>
                        <h3 className="text-xl font-semibold mb-2">AI-Powered Insights</h3>
                        <p className="text-gray-600">
                            Unique perspectives and recommendations generated by advanced AI
                        </p>
                    </MotionDiv>

                    {/* Visual Stories */}
                    <MotionDiv
                        whileHover={{ y: -10 }}
                        className="p-6 rounded-2xl bg-white shadow-xl"
                    >
                        <div className="h-12 w-12 bg-pink-100 rounded-xl flex items-center justify-center mb-4">
                            <span className="text-2xl">🎨</span>
                        </div>
                        <h3 className="text-xl font-semibold mb-2">Visual Stories</h3>
                        <p className="text-gray-600">
                            Stunning AI-generated visuals that bring destinations to life
                        </p>
                    </MotionDiv>

                    {/* Smart Recommendations */}
                    <MotionDiv
                        whileHover={{ y: -10 }}
                        className="p-6 rounded-2xl bg-white shadow-xl"
                    >
                        <div className="h-12 w-12 bg-blue-100 rounded-xl flex items-center justify-center mb-4">
                            <span className="text-2xl">🎯</span>
                        </div>
                        <h3 className="text-xl font-semibold mb-2">Smart Recommendations</h3>
                        <p className="text-gray-600">
                            Personalized travel suggestions based on your preferences
                        </p>
                    </MotionDiv>
                </div>
            </div>
        </section>
    );
} 